### PR TITLE
Explains setting up Sentry and other Docker apps

### PR DESCRIPTION
**Pull request by OKNoah**

### CODE REVIEW

**Comment by OKNoah** [comment]
Bump?

**Comment by josegonzalez** [comment]
Good bump! I'll set a reminder for reviewing this tomorrow :)

**Comment by OKNoah** [comment]
@josegonzalez Ignore the tiny amount of typos (joke). What I want to know is if it's a topic you want to publish. Does it need to be de-editorialized? If you think it has promise, or think it needs another direction, let me know. After that, I'm confident I can proof and condense it before I give you or anyone else the task of scrutinizing the final copy.

**Comment by OKNoah** [comment]
°

**Pull request closed without merging**
